# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: publish_on_pages

on:
  push:
    tags: 'v\d+'

jobs:
  createIssue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: git config --global user.name $user_name
      - run: git config --global user.email $user_email
      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create issue
        id: issue_text
        run: |
          echo "::set-output name=issue_text::$(cat << EOF
          #Release ${GITHUB_REF#refs/*/} by ${{ github.event.actor }}

          ##Date:  ${{ steps.date.outputs.date }}

          You can see deployment history [here](https://github.com/Lagushka/unit-demo-cra/deployments/activity_log?environment=github-pages)
          EOF
          )"
      - run: gh issue create --title ${GITHUB_REF#refs/*/} --label "RELEASE" --body "${{ steps.issue_text.outputs.issue_text }}"
    env: 
      user_name: 'github-actions[bot]'
      user_email: 'github-actions[bot]@users.noreply.github.com'
      GH_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
      repository: ${{ github.event.repository.name }}

  publish:
    runs-on: ubuntu-latest
    env: 
      user_name: 'github-actions[bot]'
      user_email: 'github-actions[bot]@users.noreply.github.com'
      github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
      repository: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - run: npm run e2e
      - run: git config --global user.name $user_name
      - run: git config --global user.email $user_email
      - run: git remote set-url origin https://${github_token}@github.com/${repository} 
      - run: npm run deploy -- -m ${GITHUB_REF#refs/*/}
      - run: echo "tag=${GITHUB_REF#refs/*/}"
